# Generated by Django 2.0.5 on 2018-07-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_goods_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods',
            new_name='good',
        ),
    ]
