# Generated by Django 2.0.5 on 2018-07-22 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=300, verbose_name='密码')),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
